### ISSUE TITLE
bump up versions of project dependencies

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#14]

**Comment by lchorbadjiev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SP20: [gpf] bump up versions of project dependencies](https://trello.com/c/mrHCKCpl/957-sp20-gpf-bump-up-versions-of-project-dependencies)

**Comment by iordanivanov** [comment]
https://trello.com/c/2a1hmcxy/970-sp20-update-django-version
