### ISSUE TITLE
Download in dataset statistics, families by pedigree isn't working

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpf#285]

**Comment by joankosev** [comment]
![Image](https://user-images.githubusercontent.com/50270882/201112912-1c888da6-7d81-40d1-8743-a4bc85adc5af.png)

**Comment by IvoTod** [comment]
The `/api/v3/common_reports/families_data/download` route was removed and merged with `/api/v3/common_reports/families_data/<dataset_id>` route and should be changed on the front end.
