### ISSUE TITLE
[BUG] Import tools CLI returns a non-zero value when successfully importing a study

### ISSUE THREAD

**Issue by IvoTod** [iossifovlab/gpf#395]
**What happened**:
Following the [Getting Started guide](https://www.iossifovlab.com/gpfuserdocs/administration/getting_started.html#example-import-of-de-novo-variants-helloworld) and executing the `import tools denovo_helloworld.yaml` script, after successfully executing, it returns True, which turns into a false positive that misleads users into thinking something went wrong.

**What you expected to happen**:
It should properly return 0 so it doesn't seem like an error has occured.

**Minimal Complete Verifiable Example**:
The getting started guide step linked above is a quick and easy example.

**Comment by svetlin-mladenov** [comment]
Fix in #396
