### ISSUE TITLE
[BUG] Missing AGRE gene set phenotype data

### ISSUE THREAD

**Issue by IvoStefanov** [iossifovlab/gpf#415]
**What happened**:
![image](https://user-images.githubusercontent.com/71064753/228497514-000b4db8-ef41-4632-8172-a8f431d29005.png)

**What you expected to happen**:
Show AGRE gene set phenotype data and corresponding checkboxes

**Minimal Complete Verifiable Example**:
Seen on every dataset/study on production instance

**Comment by lchorbadjiev** [comment]
seqclust data restored.
